# Generated by Django 4.2 on 2023-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchday360", "0003_match_matchday_date_match_matchday_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchday",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
