# Generated by Django 4.2 on 2023-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchday360", "0004_matchday_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
