# Generated by Django 4.2 on 2023-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchday360", "0005_alter_team_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="matchday_date",
            field=models.DateField(),
        ),
    ]
